xarm:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    position: 
      xarm_2_joint:
        type: position_controllers/JointPositionController
        joint: xarm_2_joint
       
      xarm_3_joint:
        type: position_controllers/JointPositionController
        joint: xarm_3_joint
     
      xarm_4_joint:
        type: position_controllers/JointPositionController
        joint: xarm_4_joint
             
      xarm_5_joint:
        type: position_controllers/JointPositionController
        joint: xarm_5_joint
      
      xarm_6_joint:
        type: position_controllers/JointPositionController
        joint: xarm_6_joint
       
    trajectory:
      type: "position_controllers/JointTrajectoryController"
      joints:
        - xarm_6_joint
        - xarm_5_joint
        - xarm_4_joint
        - xarm_3_joint
        - xarm_2_joint 
        
      constraints:
          goal_time: 2
          stopped_velocity_tolerance: 10.0
          xarm_6_joint: {trajectory: 2.0, goal: 2.1}
          xarm_5_joint: {trajectory: 2.0, goal: 2.1}
          xarm_4_joint: {trajectory: 2.0, goal: 2.1}
          xarm_3_joint: {trajectory: 2.0, goal: 2.1}
          xarm_2_joint: {trajectory: 2.0, goal: 2.1}
          
      stop_trajectory_duration: 0.5
      allow_partial_joints_goal: true    

    
    gripper: 
      type: "position_controllers/GripperActionController"
      joint:
        xarm_1_joint 
